package com.ims.webService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2020-05-27T21:52:56.900+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "HelloServiceService", 
                  wsdlLocation = "http://192.168.1.3/service/helloService?wsdl",
                  targetNamespace = "http://webService.ims.com/") 
public class HelloServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webService.ims.com/", "HelloServiceService");
    public final static QName HelloServicePort = new QName("http://webService.ims.com/", "HelloServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.3/service/helloService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.3/service/helloService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServicePort")
    public HelloService getHelloServicePort() {
        return super.getPort(HelloServicePort, HelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloService
     */
    @WebEndpoint(name = "HelloServicePort")
    public HelloService getHelloServicePort(WebServiceFeature... features) {
        return super.getPort(HelloServicePort, HelloService.class, features);
    }

}
