
package com.ims.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServiceImpl", targetNamespace = "http://impl.webService.ims.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "say", targetNamespace = "http://impl.webService.ims.com/", className = "com.ims.webService.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://impl.webService.ims.com/", className = "com.ims.webService.SayResponse")
    @Action(input = "http://impl.webService.ims.com/HelloServiceImpl/sayRequest", output = "http://impl.webService.ims.com/HelloServiceImpl/sayResponse")
    public String say(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
