package com.java1234.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2019-08-12T14:35:10.749+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://webservice.java1234.com/", name = "HelloWorldService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldService {

    @WebMethod
    @RequestWrapper(localName = "say", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://webservice.java1234.com/", className = "com.java1234.webservice.SayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String say(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
